### ISSUE TITLE
Prática Git : Juliana de Carvalho, Clara Azar, Anderson Machado e Felipe Andrade

### ISSUE THREAD

**Issue by Ju-Carvalho** [leouieda/matematica-especial#1]
https://github.com/Ju-Carvalho/pr-tica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **7**
- [x] Tarefa bônus (vale 1 pt extra): **0**

**Comment by victortxa** [comment]
@Ju-Carvalho  indique se vocês são da turma 1 ou 2.

**Comment by Ju-Carvalho** [comment]
Turma1

2015-09-17 10:29 GMT-03:00 victortxa notifications@github.com:

> @Ju-Carvalho https://github.com/Ju-Carvalho indique se vocês são da
> turma 1 ou 2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/leouieda/matematica-especial/issues/1#issuecomment-141085680
> .

## 

Juliana de Carvalho
Estudante de Graduação em Oceanografia.

**Comment by Ju-Carvalho** [comment]
turma 1

**Comment by leouieda** [comment]
@andersonrmachado @Ju-Carvalho @felipesurf @clarazar
Nota: 10
