### ISSUE TITLE
Pratica git: Rafael Lapagesse, Leandro Nogueira - Turma 1

### ISSUE THREAD

**Issue by rafaellapagesse** [leouieda/matematica-especial#10]
Rafael do Rego Barros Lapagesse Alves Corrêa
Leandro Nogueira

https://github.com/rafaellapagesse/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **1**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Leandro deveria ter [feito esse commit](https://github.com/rafaellapagesse/pratica-git/commit/8b9529150d91590b43f90c50e6770472ef04af9e)
- Não seguiu as instruções da prática nem fez as tarefas devidamente

**Comment by leouieda** [comment]
@rafaellapagesse 
Nota: 4
