### ISSUE TITLE
Prática Funções e Programação Defensiva - Maria Carolina e Tatiane (turma 2)

### ISSUE THREAD

**Issue by Tahmira** [leouieda/matematica-especial#101]
https://github.com/mat-esp-uerj/funcoes-maria-tatiane.git

A prática foi realizada sem grandes problemas, mas acabou demorando demais porque só tinham duas pessoas, então acabamos não fazendo a tarefa bônus.
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **2**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **3.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentarios
- Pode-se chamar uma ou mais funções dentro de outra função. Isso é o que deveria ter sido feito em **Composição de Funções**.
- Na **Checagem de Outputs** não verificou o que fez. Por exemplo, `100ºC = 212ºF`, porém colocou a mensagem `Falso` neste teste e no anterior. Faltou um pouco de atenção.
- Nos dois últimos testes de `msoma`, apesar de estar usando `np.allclose`, colocou matrizes com dimensões diferentes. Isso fez com que o teste desejado não fosse realizado, já que ocorreu um `AssertionError`.
- Faltaram exemplos nas docstrings das matrizes

**Comment by leouieda** [comment]
Nota: 8.5
@Tahmira
