### ISSUE TITLE
Prática git Arthur, Breno, Gabriel

### ISSUE THREAD

**Issue by lemosgabr** [leouieda/matematica-especial#11]
https://github.com/lemosgabr/pratica-git
alunos arthur gabriel breno
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **2**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Quem é @jorge157? Tem um commit em seu nome mas não consta no alunos.txt
- Prática ficou pela metade. Faltou colocar versão do professor e gerar e resolver o conflito nos commits. Faltou arquivo intro-git.txt
- Confusão com relação ao Gabriel que não possui commits no repositório.

**Comment by victortxa** [comment]
@lemosgabr indique se vocês são da turma 1 ou 2.

**Comment by leouieda** [comment]
@lemosgabr Por favor escreva seus nomes completos aqui.

**Comment by leouieda** [comment]
@Chapaman, @BrenoHenrique e @jorge157 atenção as questões levantadas acima.

Quem é @lemosgabr? Por que o repositório está na conta dessa pessoa se [não há commits nesse nome](https://github.com/lemosgabr/pratica-git/commits/master)?

**Comment by lemosgabr** [comment]
olá professor,
@lemosgabr é o meu login do github. Eu fazia grupo nas primeiras práticas com o Breno e o Arthur, e todas as práticas foram feitas no meu notebook, no entanto quem mais dominava os conceitos passados pelo senhor era o arthur, então os commits foram feitos no nome dele. Agora estou em outro grupo com o Marcos e a Karina e ja "conectei" minha conta github no repositório online do grupo novo.
att Gabriel Lemos

Date: Thu, 1 Oct 2015 14:34:37 -0700

**Comment by leouieda** [comment]
Nessa prática quem trabalhou e está registrado é @Chapaman, @BrenoHenrique e @jorge157. Por que o @jorge157 possui um commit se ele não faz parte do grupo?

Gabriel, a tarefa é para **TODOS** fazerem, não para quem já sabe. Eu diria que é principalmente para quem **não** sabe ainda. Se você não fizer nada, não importa o motivo, **não receberá nota**. Já falei isso várias vezes durante as aulas. Como essa foi a primeira prática eu darei um desconto. Mas **fique atento** pois não terão mais descontos. Não vacile.

**Comment by leouieda** [comment]
@Chapaman, @BrenoHenrique, @jorge157 e @lemosgabr vocês tem até sexta-feira (10/10) para responder as questões acima (minha e do @victortxa). **Caso não respondam, vou considerar essa prática como anulada.**

**Comment by lemosgabr** [comment]
Ta ok, professor. Obrigado e desculpe qualquer coisa.
att
Gabriel L.

Date: Wed, 7 Oct 2015 06:29:50 -0700

**Comment by Chapaman** [comment]
@victortxa @leouieda Olá! Eu sou o Arthur Mendes Romeu e sou da turma que tem aula na quarta e quinta (turma1).

**Comment by Chapaman** [comment]
Eu estou meio perdido :/ 
As questões que você mencionou eram referentes à nome e turma, certo?
Esse link https://github.com/lemosgabr/pratica-git contém só as coisas das primeiras aulas? Me falha a memória agora se isso foi separado das atividades em que tínhamos que fazer os gráficos e escrever o bubble sort em python ou não. Nosso grupo ficou um tanto quanto desunido no sentido de saber exatamente o que faltava para terminar as atividades, então eu realmente espero que tenhamos feito tudo.

**Comment by leouieda** [comment]
@Chapaman esse repositório deveria conter somente a prática de git. Se organize melhor com o novo grupo para não ficar na dúvida. Trabalho em equipe é parte do aprendizado.

**Leia** as questões no topo dessa Issue:

> @lemosgabr indique se vocês são da turma 1 ou 2.
> 
> @lemosgabr Por favor escreva seus nomes completos aqui.

**Comment by lemosgabr** [comment]
ola professor meu nome completo é Gabriel Lemos e estou na turma 1 ( aulas quartas e quintas)

Date: Thu, 8 Oct 2015 05:10:41 -0700

**Comment by leouieda** [comment]
@Chapaman @lemosgabr @BrenoHenrique
Nota: 5
