### ISSUE TITLE
Prática git: Karina, Marília, Paula

### ISSUE THREAD

**Issue by paulamarangoni** [leouieda/matematica-especial#112]
Karina Pereira
Marilia Cardoso
Paula Marangoni
Link: https://github.com/paulamarangoni/mat-esp-python-intro-2015

Obs: Desculpe o atraso. Houve algum erro durante a criação da issue.
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [ ] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): *\* *\* 
- [ ] Repositório atende exatamente as especificações da prática (vale 7 pt): *\* **
- [ ] Tarefa bônus (vale 1 pt extra): *\* **

**Comment by KarinaPereira** [comment]
@victortxa @leouieda

**Comment by victortxa** [comment]
@paulamarangoni @KarinaPereira O link acima não é da prática de Git, mas dá primeira prática de Python. Deem uma olhada novamente. Nâo precisa criar uma nova Issue, basta editar acima e colocar o link certo.

**Comment by leouieda** [comment]
@paulamarangoni @KarinaPereira leiam o que vocês escrevem. Não houve erro, simplesmente falta de atenção.

**Comment by leouieda** [comment]
Fechei essa issue para não ficar duplicado com a #3
