### ISSUE TITLE
minimos quadrados: Adélia, Itamar, Felipe Andrade

### ISSUE THREAD

**Issue by adeliarocha** [leouieda/matematica-especial#114]
turma 1
https://github.com/mat-esp-uerj/minimos-quadrados-itafedelia.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0.5**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **2**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **0**

**Comment by victortxa** [comment]
@leouieda quando corrigir dê uma olhada nos comentários dá primeira função e na tarefa bônus. Depois olha nesse aqui: https://github.com/mat-esp-uerj/minimos-quadrados-barbara-juliana-glo/blob/master/minimos-quadrados.ipynb (pertence a este https://github.com/leouieda/matematica-especial/issues/107). Pode olhar também as funções `mtrans`, `mmult`.

**Comment by leouieda** [comment]
Pode deixar.

## 

Leonardo Uieda

Professor - Faculdade de Geologia
Universidade do Estado do Rio de Janeiro (UERJ)
http://www.leouieda.com

**Comment by leouieda** [comment]
@victortxa vou invalidar a tarefa bonus desse grupo. O commit que introduz a bonus deles [foi feito no dia 11/01/2016](https://github.com/mat-esp-uerj/minimos-quadrados-itafedelia/commit/e44f8e380fe98a09ca703b11eabc33dd859b44c4). O commit com a bonus do #107 [foi feito em 03/12/2015](https://github.com/mat-esp-uerj/minimos-quadrados-barbara-juliana-glo/commit/314cf39778a6e9e873d5f6f729513724bf1413b7). Logo, o desse não é o original.

**Comment by leouieda** [comment]
~~Nota: 8.5~~
@adeliarocha

**Comment by leouieda** [comment]
**Retificando**. Houve cópia de tarefa da solução #107, como evidenciada pelos commits mencionado acima. O código de conduta da disciplina diz claramente que em caso de **plágio** a prática receberá 0 (https://github.com/leouieda/matematica-especial#pl%C3%A1gio). 

Nota: 0
@adeliarocha
