### ISSUE TITLE
sistemas-lineares-karina-rafael-sidharta

### ISSUE THREAD

**Issue by KarinaPereira** [leouieda/matematica-especial#119]
Julio Cabaleiro Vianna, Karina dos Santos Pereira, Rafael do Rego Barros Lapagesse Alves Correa, Sidharta (Turma 1)

https://github.com/mat-esp-uerj/sistemas-lineares-karina-rafael-sidharta
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [ ] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): *\* *\* 
- [ ] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): *\* **
- [ ] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): *\* **
- [ ] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): *\* **
- [ ] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): *\* **
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **0**

**Comment by victortxa** [comment]
@KarinaPereira Falta o link do repositório.

**Comment by KarinaPereira** [comment]
Desculpa
https://github.com/mat-esp-uerj/sistemas-lineares-karina-rafael-sidharta

**Comment by leouieda** [comment]
@KarinaPereira mais uma? vocês abriram 3 issues: essa, #128 e #147

**Comment by KarinaPereira** [comment]
Desculpa professor @leouieda, desconsidera essa, erro meu. Pensei que não tínhamos feito!

**Comment by leouieda** [comment]
Sem problemas, essa eu não cheguei a corrigir pelo menos.
