### ISSUE TITLE
pratica git: adélia, daniela, ronan e bárbara

### ISSUE THREAD

**Issue by adeliarocha** [leouieda/matematica-especial#12]
turma 1

https://github.com/adeliarocha/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **2.5**
- [x] Tarefa bônus (vale 1 pt extra): **0.5**
### Comentários
- Commits fora da ordem das tarefas.
- Não mudou de integrante do grupo nas etapas que a tarefa indicava.
- Não alterou bubble-sort para conter as 3 versões do algoritmo
- Cuidado com a linguagem usada nas respostas. Também poderia omitir o 'foi' nas mensagens de commit.

**Comment by adeliarocha** [comment]
https://github.com/adeliarocha

**Comment by leouieda** [comment]
@adeliarocha por favor coloque o link do repositório em sí, esse ai é o da sua conta.

**Comment by leouieda** [comment]
@adeliarocha @danielaalvim @RONANOLIVEIRA @barbara-lisboa 
Nota: 6
