### ISSUE TITLE
Prática Python Intro: Julio Vianna, Rafael Lapagesse, Daniel Rosselli, Turma 1

### ISSUE THREAD

**Issue by juliocabaleiro** [leouieda/matematica-especial#123]
https://github.com/juliocabaleiro/mat-esp-python-intro-2015.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **2**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **2.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Tarefa 1 feita, mas a  Tarefa 2 não.

**Comment by victortxa** [comment]
@juliocabaleiro Deem uma conferida, pois apenas a Tarefa 1 está feita no repositório que vocês forneceram.

**Comment by juliocabaleiro** [comment]
Você está na sala vitor ? Quando eu clico no link que está na issue ele joga direto para o repositório respectivo.Para mim estava certo

Date: Wed, 13 Jan 2016 09:22:50 -0800

**Comment by leouieda** [comment]
@juliocabaleiro essa prática já foi. Os problemas maiores eram quando não conseguimos abrir o repositório. Não foi esse o seu caso. Não se preocupe.

**Comment by leouieda** [comment]
@juliocabaleiro @rafaellapagesse @danielrosselli 
Nota: 7.5
