### ISSUE TITLE
Prática Git - Carol, Flávia e Silas 

### ISSUE THREAD

**Issue by silaxsilva** [leouieda/matematica-especial#13]
https://github.com/silaxsilva/pratica-git
Turma 1
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **2** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **3.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Mensagens de commit pouco informativas. Por exemplo, "alteracao do arquivo"
- Tarefas faltando: versão bubblesort simplificada, versão do professor, gerar e resolver o conflito no bubble-sort.
- Instruções sobre o git deveriam estar em intro-git.txt não intro-shell.txt

**Comment by leouieda** [comment]
@silaxsilva @carolnabuco @Fstreva
Nota: 5.5
