### ISSUE TITLE
Prática phyton-intro-2 - Marcela, Angélica, Carlos Eduardo e Julyana Marapodi

### ISSUE THREAD

**Issue by Marcelarclaudio** [leouieda/matematica-especial#136]
https://github.com/mat-esp-uerj/python-intro-2-aguaviva.git

**Comment by victortxa** [comment]
issue duplicada https://github.com/leouieda/matematica-especial/issues/48

**Comment by Marcelarclaudio** [comment]
como assim?

**Comment by victortxa** [comment]
@Marcelarclaudio clica no link no comentário acima...

**Comment by Marcelarclaudio** [comment]
foi mal, ja me perdi nesses issues
