### ISSUE TITLE
Pratica Git- Lucas silva, Marcos Clemente e Willian Soares

### ISSUE THREAD

**Issue by luquinhas317** [leouieda/matematica-especial#14]
https://github.com/luquinhas317/pratica-git
Turma 1
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **5.5**
- [x] Tarefa bônus (vale 1 pt extra): **0.5**
### Comentários
- Atenção no uso de símbolos (~, ^, ' etc). Isso pode causar problemas.
- Não causou e resolveu o conflito que deveria aparecer [nesse commit](https://github.com/luquinhas317/pratica-git/commit/5747bae73fa7cf1659410c244337f3640ef10427)
- Faltou o arquivo intro-git.txt

**Comment by adeliarocha** [comment]
@leouieda https://github.com/adeliarocha/pratica-git

**Comment by leouieda** [comment]
@luquinhas317 @marcosclemente
Nota: 9
