### ISSUE TITLE
pratica 2 - camila-tatiane-turma2

### ISSUE THREAD

**Issue by camilareveles** [leouieda/matematica-especial#145]
https://github.com/camilareveles/mat-esp-python-intro-2015.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **0.5**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1.5**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **2.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Colocou valores na mão para fazer gráficos, isso seria evitado se o gráfico estivesse antes do ordenamento da lista.
- Não imprime original
- figuras faltando
- figuras erradas

**Comment by camilareveles** [comment]
enviei errado!

**Comment by camilareveles** [comment]
por favor, desconsiderem essa issue

**Comment by victortxa** [comment]
@camilareveles mas tem outra sua dessa prática? Não vi na lista de Issues.

**Comment by camilareveles** [comment]
@victortxa, as primeiras práticas não era feitas por issues, por isso tirei. 
Não era assim?
Eu tenho todas as práticas comigo (sou aquela aluna que na primeria prática, a aluna que era minha dupla saiu da disciplina e minha tarefa estava com ela, e depois na segunda pratica meu computador foi formatado e perdi o que havia feito).
Não estou sabendo como colocá-las em issues. Elas não tem aquele link de grupos que tivemos nas outras praticas (a partir da pratica 3 se nao me engano) 

Mandei um email pro leonardo perguntando tambem mas ainda estou esperando resposta.

**Comment by victortxa** [comment]
@camilareveles você fez certo em abrir a issue, isso deve ser feito para **todas** as práticas. 
O que mudou, a partir da 3ª prática (Intro Python II) , foi que vocês não precisavam mais criar o repositório. Quando vocês clicavam no link do email, depois de vocês criarem o grupo ou entrarem em um existente, o repositório da prática era criado automaticamente.
Confere se você ou seu grupo criaram as issues correspondentes a cada prática feita, senão faça isso o mais rápido possível. Neste link você veem todas e podem usar a busca para filtrar, além de poder usar a `milestones` (ao lado de `labels`) para filtrar por prática: https://github.com/leouieda/matematica-especial/issues. Repare que na página da disciplina (https://github.com/leouieda/matematica-especial) em **Entrega das Soluções** tem as instruções.
Estou reabrindo aqui.
PS.: o Léo chamou atenção para a abertura da issues em dois email essa semana. Se possível reforce com o restante das pessoas. O prazo é amanhã.

**Comment by camilareveles** [comment]
que bom então @victortxa , já reabri. Uma pena que não estou encontrando a primeira... mas está tudo no meu pc (inlcusive as figuras geradas). Como proceder?

**Comment by victortxa** [comment]
@camilareveles vê se você já não tem em algum repositório do github ou se alguém do seu grupo não tem. 
Caso não, basta você criar o repositório e dar um git push, mas **ANTES** terá que dar um `git remote set-url ENDERECO-DO-REPOSITORIO`, para indicar para o git para onde será enviado o repositório ao dar o `git push`.
Qualquer coisa estarei amanhã na uerj. Pela tarde será mais fácil, devo estar lá até umas 18h.

**Comment by camilareveles** [comment]
obrigada!!

**Comment by leouieda** [comment]
Nota final: 6.5
@camilareveles
