### ISSUE TITLE
Prática git: Dyellen, Cadu, André

### ISSUE THREAD

**Issue by dyyhqueiroz** [leouieda/matematica-especial#15]
Dyellen Soares Queiroz
Carlos Eduardo Veríssimo Ribeiro
André Pellicciotta Facchinei

link:https://github.com/dyyhqueiroz/pratica-git.git
Turma 2
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **6**
- [x] Tarefa bônus (vale 1 pt extra): **0.5**
### Comentários
- [commit de resolução de conflitos](https://github.com/dyyhqueiroz/pratica-git/commit/76d86c1231bd2efb117184f87256bcbdf9243c52) incompleto. Faltou remover os `>>>>>HEAD` etc.

**Comment by leouieda** [comment]
@dyyhqueiroz @dukbom @Facchinei 
Nota: 9.5

**Comment by leouieda** [comment]
Só para confirmar, o @Facchinei deixou a disciplina correto?

**Comment by dukbom** [comment]
Exatamente ! Ele teve um pequeno problema com a disciplina no periodo
anterior mas
conseguiu reaver a passar nela, por isso ele não continuou.

Cadu

2016-01-12 16:36 GMT-02:00 Leonardo Uieda notifications@github.com:

**Comment by leouieda** [comment]
Certo. Obrigado @dukbom
