### ISSUE TITLE
Prática git: Ana Paula, Angélica, Letícia

### ISSUE THREAD

**Issue by lemarinho** [leouieda/matematica-especial#16]
Turma 2
https://github.com/lemarinho/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **6**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Faltou arquivo intro-git.txt
- Faltou nomes completos no alunos.txt

**Comment by leouieda** [comment]
@lemarinho @anapn
Nota: 9
