### ISSUE TITLE
Pratica Git: Breno, Douglas e Jonatan

### ISSUE THREAD

**Issue by DouglasPF** [leouieda/matematica-especial#17]
Douglas Parreira de Freitas
Jonatan Henrique Nascimento
Breno de Brito Fontel
https://github.com/DouglasPF/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Faltou tarefa de adicionar versão do bubble sort de vocês simplificada
- Faltou gerar e resolver o conflito no arquivo bubble-sort

**Comment by leouieda** [comment]
@DouglasPF por favor indique a qual turma vocês pertencem

**Comment by DouglasPF** [comment]
Turma 2, já coloquei no Git!

Date: Fri, 18 Sep 2015 12:25:02 -0700

**Comment by leouieda** [comment]
@DouglasPF @Brenofontel @Jonatanrik 
Nota: 8
