### ISSUE TITLE
Prática Matrizes e Vetores - Karina, Marcos, Thaís e Gabriel

### ISSUE THREAD

**Issue by thaispeccini** [leouieda/matematica-especial#170]
https://github.com/mat-esp-uerj/matrizes-vetores-karina_marcos_thais.git

tarefa feita no tempo proposto porém não demos issues.
Integrantes:
Karina Pereira
Marcos Vinicius
Thaís Peccini
Gabriel lemos

turma 1

obs: o arquivo alunos.txt está sem o nome de um integrante do grupo: Thaís Peccini pois esquecemos e edita-lo.
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **0.5**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **2**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **2**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Na primeira tarefa foi feita apenas a impressão. A variável `C` não está com o resultado da soma das matrizes. Faltou atenção.
- Na última tarefa o resultado deveria ser uma matriz e não um vetor.

**Comment by leouieda** [comment]
Nota: 5.5
@thaispeccini
