### ISSUE TITLE
Pratica Capstone: Itamar, Gustavo, William e Breno

### ISSUE THREAD

**Issue by ogoshi** [leouieda/matematica-especial#171]
Turma 1.
https://github.com/mat-esp-uerj/capstone-gameover.git

OBS: Professor, estou enviando o issue hoje pois eu não estava conseguindo achar o caminho para fazer o mesmo via github, aí um colega me falou que o senhor havia mandado um link , fui conferir e estou aqui  :+1: 
Itamar Almeida.

**Comment by victortxa** [comment]
Issue duplicada https://github.com/leouieda/matematica-especial/issues/162
