### ISSUE TITLE
Pratica 1 - Gleyson, Nikolas, Thais Abdias

### ISSUE THREAD

**Issue by Abdiasthais** [leouieda/matematica-especial#179]
https://github.com/mat-esp-2016/intro-git-gnt.git

## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Qualidade das mensagens de commit (explica o que foi feito com detalhe suficiente) [vale 5 pt]: 5

Seguiu fielmente as instruções abaixo (nomes dos arquivos estão corretos, todos os passos foram seguidos, etc) [vale 5 pt]

- [x] Adicione no repositório um arquivo `alunos.txt` com os nomes completos de  cada membro do grupo e seus nomes de usuário no github.com [vale 1 pt] 1
- [x] Crie um arquivo `bubblesort.txt` e escreva as instruções que vocês criaram para ordenar 5 cartas [vale 1 pt]: 1 
- [x] Edite o arquivo `bubblesort.txt` para que ele contenha a versão do  algoritmo passo a passo (não a versão simplificada) que o professor escreveu durante a aula. O arquivo não deve mais conter a versão de vocês [vale 2 pt]:  2
- [x] Edite novamente o arquivo `bubblesort.txt` para conter a versão simplificada e generalizada o algoritmo [vale 1 pt]: 1

**BÔNUS**: 

- [x] Faça a mesma coisa para a versão alternativa do algoritmo bubblesort, colocando as instruções em um arquivo chamado `bubblesort-alt.txt` [vale 1 pt]: 1

**Comment by leouieda** [comment]
Nota: 10
