### ISSUE TITLE
Prática git Maria Carolina, Guilherme Malagutti e Luiz Henrique Turma 2

### ISSUE THREAD

**Issue by henriqueocn** [leouieda/matematica-especial#18]

**Comment by henriqueocn** [comment]
Guilherme Malagutti de Castro
Maria Carolina Chalegre Touceira
Luiz Henrique Gomes da Silva
https://github.com/henriqueocn/pratica-git

## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **6**
- [x] Tarefa bônus (vale 1 pt extra): **1**

### Comentários
- [Commit de resolução de conflitos](https://github.com/henriqueocn/pratica-git/commit/5b94a521e87e4e24302bd32ac5c1468f674bbcf9) não finalizado. Faltou remover os `>>>>>HEAD` etc.

**Comment by leouieda** [comment]
@henriqueocn @Tahmira @guimalagutti 
Nota: 10
