### ISSUE TITLE
Cronograma das aulas de Python

### ISSUE THREAD

**Issue by leouieda** [leouieda/matematica-especial#185]
@victortxa estou revendo o cronograma das praticas de python. Estou com os seguintes temas. Criei uma issue em cada repositório com o que eu pretendo abordar em cada um. Gostaria da sua opinião sobre eles. Em todas eu vou tentar usar dados de temperatura desse site: http://berkeleyearth.lbl.gov/locations/23.31S-42.82W

Python 1: variáveis, bibliotecas e gráficos simples - mat-esp/python-1#1

Python 2: condições e repetindo ações  - mat-esp/python-2#4

Python 3: criando funções e programação defensiva - mat-esp/python-3#1

Python 4: extraindo informação de arquivos de texto - mat-esp/python-4#2

Python 5: scripts e argumentos de linha de comando - mat-esp/python-5#1

**Comment by victortxa** [comment]
@leouieda  acho que tudo está bem razoável. Acredito que eles consigam fazer em tempo, mas a partir da primeira prática vai dar para saber melhor como eles vão evoluir.

**Comment by leouieda** [comment]
OK. Essa primeira é a que mais me preocupa com relação ao tempo. Mas acho que se forçar um pouco vai.

**Comment by lpgm007** [comment]
Mestre Leonardo, eu concordo com as mudanças propostas no cromograma sobre a linguagem Phyton.
