### ISSUE TITLE
Prática 2: Lucas Lopes, Luís Sérgio, Felipe Dias, Romulo Porto

### ISSUE THREAD

**Issue by LucasLopesOcn** [leouieda/matematica-especial#186]
https://github.com/mat-esp-2016/python-1-python_pratica2
## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **0.5**
- [x] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos  (vale 2 pt): **1**
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **0**

Formatação do código:
- Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
- Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:
- Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
- Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by leouieda** [comment]
Nota: 8.5
