### ISSUE TITLE
Pratica 2 (python1): Gleyson, Nikolas M., Thais Abdias

### ISSUE THREAD

**Issue by gleysonXD** [leouieda/matematica-especial#189]
https://github.com/mat-esp-2016/python-1-gnt2

Muita dificuldade de preencher a linha cinza mas mesmo que não preenchidas coloquei os 95% de incerteza + e -, como 2 funções distintas 

Mesmo que não receba o ponto completo queria saber como fazer certo essa parte de preencher o gráfico entrelinhas 

## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **1**
- [x] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **0**
- [x] Nomes de variáveis descritivos  (vale 2 pt): **2**
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **3** (`plt.plot (anos, 25 + anomaly_ano`: deveria ser anos decimais e de onde vem esse 25?)
- [x] Tarefa bônus (vale 1 pt extra): **1** (muito bom!)

Formatação do código:

* Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
* Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:

* Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
* Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by leouieda** [comment]
Como preencher entre duas linhas: http://matplotlib.org/examples/pylab_examples/fill_between_demo.html

**Comment by leouieda** [comment]
Nota: 8
