### ISSUE TITLE
Pratica git: João, Paulo, Leonardo - Turma 2

### ISSUE THREAD

**Issue by Pauloq** [leouieda/matematica-especial#19]
João Pedro Marvila Padilha Pitta
Paulo Ricardo Radha Ramana Quintella da Silva
Leonardo Vieira Soares Ferreira

https://github.com/Pauloq/pratica-git.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **5.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- [Commit de resolução de conflito](https://github.com/Pauloq/pratica-git/commit/fc1e453cf643a75cd646b330177eb05ee8aa6433) não está indicado como tal.
- alunos.txt faltando 1 nome
- Faltou arquivo intro-git.txt

**Comment by leouieda** [comment]
@Pauloq @leovsf @JPedroMarvila 
Nota: 8.5
