### ISSUE TITLE
Prática 2: Victor, Bruna, Douglas

### ISSUE THREAD

**Issue by dgmilanez** [leouieda/matematica-especial#194]
https://github.com/mat-esp-2016/python-1-vbd

Não conseguimos deixar o nosso gráfico idêntico ao da tarefa.
Ficaram faltando:
- Modificar a escala para de 20 em 20 anos, começando antes de 1820 e terminando um pouco depois de 2000.
- O tamanho do gráfico para uma janela maior.
- A legenda da temperatura ficou do lado esquerdo e não do direito(apesar dos valores estarem corretos como na tabela de dados, no gráfico da tarefa os valores estão diferentes).

Além disso, na tarefa bônus, não conseguimos utilizar o intervalo de mais ou menos duas incertezas.
## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **1**
- [x] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **1*
- [x] Nomes de variáveis descritivos  (vale 2 pt): **2**
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **4**
- [x] Tarefa bônus (vale 1 pt extra): **0.5**

Formatação do código:
- Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
- Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:
- Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
- Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

Problemas encontrados:

* `tempo = ( anos + ( meses / 12))` o certo seria `tempo = ( anos + (meses - 1) / 12)`

**Comment by leouieda** [comment]
Nota: 9.5
