### ISSUE TITLE
Pratica-git : Fernanda Ferreira, Mariana Santos e Thiago Veloso

### ISSUE THREAD

**Issue by SkulblakaVarden** [leouieda/matematica-especial#2]
Fernanda Ferreira, Mariana de Faria Santos   e Thiago Veloso Franklin.
Turma 1.
https://github.com/SkulblakaVarden/Pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **7**
- [x] Tarefa bônus (vale 1 pt extra): **0.5**
### Comentários
- Fez somente uma das atividades bônus.

**Comment by victortxa** [comment]
@SkulblakaVarden  indique se vocês são da turma 1 ou 2.

**Comment by leouieda** [comment]
@SkulblakaVarden notal final: **10**
