### ISSUE TITLE
Pratica git: Felipe, Gabi e André, turma 2

### ISSUE THREAD

**Issue by FelipeLage** [leouieda/matematica-especial#20]
https://github.com/FelipeLage/pratica-git

André Mejia Grijó, Felipe Lage e Gabriela Prates 
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **7**
- [x] Tarefa bônus (vale 1 pt extra): **1**
### Comentários
- Gostei como [esse commit](https://github.com/FelipeLage/pratica-git/commit/1b4cf6c57364467becd79ab32f2db90bf786f6c4) foi usado para arrumar o anterior. Mostra entendimento do git.

**Comment by leouieda** [comment]
@FelipeLage @andregrijo62 @gabrielateixeira 
Nota: 10
