### ISSUE TITLE
Prática 3 (python2): Gleyson M., Thais Abdias, Nikolas M.

### ISSUE THREAD

**Issue by gleysonXD** [leouieda/matematica-especial#202]
https://github.com/mat-esp-2016/python-2-gnt3.git

## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **1**
- [x] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **0**
- [x] Nomes de variáveis descritivos  (vale 2 pt): **2**
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **3.5** (`plt.savefig("Gráfico do arquivo " + arquivo[6:-3] + "png"` o nome do arquivo vai ser `Gráfico do arquivo 02S-40.98W-TAVG-Trend.png` e não foi isso que eu pedi.)
- [x] Tarefa bônus (vale 1 pt extra): **0.5** (`plt.plot (anos, anomalia_10anos`: deveria ser anos decimais)

Formatação do código:

* Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
* Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:

* Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
* Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by gleysonXD** [comment]
Professor, o gráfico ".02S-40.98W-TAVG-Trend.png" está correto com o bônus em meu computador, mas por algum motivo não foi com o ultimo push, o resto dos gráficos, igualmente com o código, estão corretos.

**Comment by leouieda** [comment]
Note que o nome começa com `.`  Por que isso? Tire esses pontos dos nomes. Os gráficos corretos devem estar no repositório.

**Comment by gleysonXD** [comment]
Começa com ponto pois eu errei na contagem de quantas letras tirar do nome e mesmo depois conseguindo perceber o erro, ajeitei o código mas não consigo deletar arquivos depois de dar o push. Na minha pasta do computador ja deletei esses gráficos e coloquei os com os nomes corretos, mas não consigo trocar pelos que ja estão no github

**Comment by leouieda** [comment]
Nota: 8
