### ISSUE TITLE
Prática Python 3 : Luiz Paulo, Rodrigo e Luís Eduardo 

### ISSUE THREAD

**Issue by Leduardobos** [leouieda/matematica-especial#211]
https://github.com/mat-esp-2016/python-3-llp007

## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **0.5**
- [x] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **0.5**
- [x] Nomes de variáveis descritivos  (vale 2 pt): **1**
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **2** (A função `matrix_2D` não usou `ano_para_ano_decimal`.  Gerou N vezes o mesmo gráfico do arquivo `'dados/0.80S-49.02W-TAVG-Trend.txt'`. Salvou com o nome errado.
- [x] Tarefa bônus (vale 1 pt extra): **0** (a tarefa bônus não era gerar gráficos)

Formatação do código:
- Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
- Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:
- Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
- Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by lpgm007** [comment]
Mais uma vez, encontramos dificuldades em trabalhar com o python, em função de definir uma função matemática para resolver e gerar um resultado satisfatório para a execução da tarefa. E  aprendemos novos conceitos e comandos.

**Comment by lpgm007** [comment]
Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de :. A nota final será informada após terminar a correção.

 Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): ** **
 Formatação do código apropriada (vale 1 pt): ** **
 Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): ** **
 Nomes de variáveis descritivos (vale 2 pt): ** **
 Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): ** **
 Tarefa bônus (vale 1 pt extra): ** **
Formatação do código:

Bom: espacamento = (maximo - minimo)/(N - 1), indices = range(0, N, 1), dado = dados[i + 1]
Ruim: espacamento=(maximo-minimo)/ (N-1), indices=range (0,N,1), dado= dados [i+ 1]
Nomes de variáveis:

Bom: temperatura, media_por_hora, anomalia, somatorio
Ruim: a, var, meh, lista
Mais detalhes em pep8.org.

**Comment by leouieda** [comment]
Nota: 5
