### ISSUE TITLE
Prática Python 4: Luiz Paulo, Luís Eduardo e Rodrigo

### ISSUE THREAD

**Issue by Leduardobos** [leouieda/matematica-especial#218]
https://github.com/mat-esp-2016/python-4-python-4-lpgler007

## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **0.5**
- [x] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **0**
- [x] Nomes de variáveis descritivos  (vale 2 pt): **0** (`open(latlong)` ao invés de `arquivo`, `qualquer`, `outra`, `open (temp)` ao invés de `arquivo`, `margem`, `locais_1`, `lc`)
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **4** (onde estão os gráficos? `margem = np.array (anual_anomalia [8:9]) [0]`? `locais_1`?)
- [x] Tarefa bônus (vale 1 pt extra): **0**

Formatação do código:

* Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
* Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:

* Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
* Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by lpgm007** [comment]
Nós encontramos muita dificuldade em criar as coordenadas geográficas de cada cidade, bem como  trabalhar com os conectivos, para manipular várias strings gerando um resultado esperado.

**Comment by lpgm007** [comment]
Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de :. A nota final será informada após terminar a correção.

 Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): ** **
 Formatação do código apropriada (vale 1 pt): ** **
 Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): ** **
 Nomes de variáveis descritivos (vale 2 pt): ** **
 Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): ** **
 Tarefa bônus (vale 1 pt extra): ** **
Formatação do código:

Bom: espacamento = (maximo - minimo)/(N - 1), indices = range(0, N, 1), dado = dados[i + 1]
Ruim: espacamento=(maximo-minimo)/ (N-1), indices=range (0,N,1), dado= dados [i+ 1]
Nomes de variáveis:

Bom: temperatura, media_por_hora, anomalia, somatorio
Ruim: a, var, meh, lista
Mais detalhes em pep8.org.

**Comment by leouieda** [comment]
Nota: 5.5
