### ISSUE TITLE
Prática 5: Bruna, Victor e Douglas

### ISSUE THREAD

**Issue by dgmilanez** [leouieda/matematica-especial#219]
https://github.com/mat-esp-2016/python-4-vbd4

Tivemos que finalizar a tarefa em um computador diferente do que geralmente trabalhamos em aula, pois o computador apresentou problemas.
O novo computador possui o Windows como sistema operacional e não Linux, com isso, no código, usamos a "\" no lugar da "/".

No momento de fazer o push final dos trabalhos, como fiz no computador de casa, o usuário que ficou registrado foi o da minha esposa(esposa do aluno Douglas Milanez): Rejane Ribeiro da Silva.

...
## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **1**
- [x] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos  (vale 2 pt): **2**
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **4.5** (Gráficos vazios novamente.)
- [x] Tarefa bônus (vale 1 pt extra): **0**

Formatação do código:
- Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
- Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:
- Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
- Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by leouieda** [comment]
Nota: 9.5
