### ISSUE TITLE
Prática git: Carla Azevedo, João Felipe Santelli, Juliana Almeida Turma 2

### ISSUE THREAD

**Issue by jfelipemaia** [leouieda/matematica-especial#22]
Carla Azevedo
João Felipe Magalhães Santelli Maia
Juliana Almeida

https://github.com/jfelipemaia/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **3**
- [x] Tarefa bônus (vale 1 pt extra): **1**
### Comentários
- 3 alunos fizeram a prática mas só tem commits no nome de 2. 
- alunos.txt com um nome a mais (Franco).
- Faltou 1 versão do bubble sort (versão de vocês simplificada)
- [Commit de resolução de conflitos](https://github.com/jfelipemaia/pratica-git/commit/5da52960e1499dcb432f92ffd43801a2e49f1f68) não terminado. Faltou tirar os `<<<<HEAD` etc.

**Comment by victortxa** [comment]
**Issue duplicada.** (Outra é #38)

**Comment by leouieda** [comment]
@jfelipemaia @carlamat1
Nota: 7
