### ISSUE TITLE
Prática 4: Lucas Lopes, Marcela Abreu.

### ISSUE THREAD

**Issue by LucasLopesOcn** [leouieda/matematica-especial#221]
https://github.com/mat-esp-2016/python-4-python-4-lucas-lopes

Professor, desculpe a demora na criação do "issue", como de costume, concluímos a tarefa, comentamos os "commits", utilizamos o comando "push" para upar os commits, mas só lembramos de criar a issue terça pela manhã antes da aula.

## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [x] Formatação do código apropriada (vale 1 pt): **0.5**
- [ ] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos  (vale 2 pt): **2**
- [x] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **5** (usar `np.nan_to_num` está  errado.
- [x] Tarefa bônus (vale 1 pt extra): **0**

Formatação do código:

* Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
* Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:

* Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
* Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by leouieda** [comment]
Nota: 9.5
