### ISSUE TITLE
Pratica-git-bruno-turma2

### ISSUE THREAD

**Issue by bsscosta** [leouieda/matematica-especial#23]
Bruno Sergio Sampaio da Costa
Julyana Marapodi Grisolia

https://github.com/bsscosta/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **1.5** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **3.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Linguagem inadequada ("otario") nas mensagens de commit
- Mensagens de commit pouco informativas. "mudei uma linha no arquivo", qual e com o que?
- Várias tarefas faltando: 3ª versão do bubble-sort, arquivo intro-git, solução de conflitos no git.

**Comment by leouieda** [comment]
@bsscosta @julyanamg 
Nota: 5
