### ISSUE TITLE
Prática 8: Thias, Carlos e Jessica

### ISSUE THREAD

**Issue by ThaisErbas** [leouieda/matematica-especial#231]
https://github.com/mat-esp-2016/matrizes-vetores-pratica8-tj.git

## Checklist de avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.

- [ ] Mensagens de commit que explicam claramente a mudança que foi feita (vale 1 pt): **1**
- [ ] Formatação do código apropriada (vale 1 pt): **0**
- [ ] Comentários no código e notebook que explicam "por que" algo foi feito e o raciocínio por trás do código (vale 1 pt): **0**
- [ ] Nomes de variáveis descritivos  (vale 2 pt): **2**
- [ ] Código produz a solução correta (exatamente como especificado na tarefa) (vale 5 pt): **5**
- [ ] Tarefa bônus (vale 1 pt extra): **0**

Formatação do código:

* Bom: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]`
* Ruim: `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]`

Nomes de variáveis:

* Bom: `temperatura`, `media_por_hora`, `anomalia`, `somatorio`
* Ruim: `a`, `var`, `meh`, `lista`

Mais detalhes em [pep8.org](http://pep8.org/).

**Comment by victortxa** [comment]
@ThaisErbas verifique se colocaram o link correto! Não nenhum commit de vocês no repositório indicado acima. Ou esse não é o link do repositório com a prática de vocês ou então esqueceram de dar `git push origin master` ou alguma outra opção.

**Comment by ThaisErbas** [comment]
@victortxa eu não sei o que houve. Também não consigo ver os commit's. Parece que é origin master, mas não estou conseguindo resolver o problema, fiz os mesmos passos que o professor fez de uma outra vez comigo, mas não está funcionando. Posso ir até o laboratório amanhã para vc me ajudar?
https://github.com/mat-esp-2016/matrizes-vetores-pratica8-tj

**Comment by victortxa** [comment]
@ThaisErbas Pode sim, mas vocês precisam verificar no computador onde fizeram a tarefa o que aconteceu. Para o Github nada foi enviado, então pode ser que vocês não tenham feito os commits no computador (para verificar basta dar o comando `git log` estando na pasta onde foi feito; caso haja commits você verá as mensagens e os nomes de quem os fez) ou não conseguido dar `git push origin master`. 
Se com o `git log` você ver que vocês fizeram os commits, então o que falta é só o `git push` mesmo. Nesse caso, dê `git remote -v` e verifique se aparece `origin https://github.com/mat-esp-2016/matrizes-vetores-pratica8-tj.git`, que no caso é o repositório para onde você está mandando os seus commits. Se não aparecer, então dê o comando: `git remote set-url origin https://github.com/mat-esp-2016/matrizes-vetores-pratica8-tj.git` para então dar `git push origin master`.

**Comment by ThaisErbas** [comment]
@victortxa Acho que consegui resolver, segui esses passos que vc enviou e está tudo de acordo. Consegui ver os commites, eu mesmo tinha feito. Só adicionei umas frases na atividade para tentar fazer um novo commit e dei o git push origin master. Obrigada!

**Comment by leouieda** [comment]
Nota: 8
