### ISSUE TITLE
Prática Python - Ana Paula, Angélica, Letícia

### ISSUE THREAD

**Issue by lemarinho** [leouieda/matematica-especial#28]
Turma 2
https://github.com/lemarinho/mat-esp-python-intro/
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **2**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **1**

**Comment by leouieda** [comment]
> 1. "Prática Python - Aluno 1, Aluno 2, Aluno 3" no título.
> 2. Qual turma vocês pertecem.
> 3. **Nomes completos de todos os integrantes do grupo.**

**Comment by lemarinho** [comment]
Ana Paula de Souza Nascimento, Angélica Roberta Costa, Letícia Alvarenga Marinho

**Comment by leouieda** [comment]
Nota final: 10
@lemarinho
