### ISSUE TITLE
pratica-git: Karina, Marília e Paula

### ISSUE THREAD

**Issue by KarinaPereira** [leouieda/matematica-especial#3]
https://github.com/201410123811/pratica-git.git

**UPDATE**: link correto https://github.com/KarinaPereira/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **5.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Repositório vazio. (**UPDATE**: corrigido com link para o repositorio correto)
- Commits iniciais usados para corrigir os nomes no arquivo. Muito bom, é para isso mesmo que serve o git
- Commits um pouco bagunçados. Não seguiram bem as instruções nas tarefas.
- Faltou uma versão do bubble-sort no antes da versão em pseudo-código.
- Faltou arquivo intro-git.txt

**Comment by maricardosop** [comment]
Turma 1 (quarta e quinta)

**Comment by leouieda** [comment]
Obrigado @maricardosop

**Comment by leouieda** [comment]
@KarinaPereira @maricardosop nota final: **0**

**Comment by KarinaPereira** [comment]
Boa noite professor.
Não entendi esse e-mail. É a minha nota da primeira tarefa? Pois eu fiz essa tarefa, assim como todas as outras, com exceção das últimas duas tarefas.
Att,Karina.

Date: Mon, 11 Jan 2016 09:22:55 -0800

**Comment by victortxa** [comment]
@KarinaPereira O repositório que você colocou na Issue está vazio. Provavelmente está no repositório de outra pessoa do seu grupo, já que você não tem outro repositório para a prática de Git ( https://github.com/KarinaPereira?tab=repositories ). Verifique e coloque o link correto nos avisando.

**Comment by KarinaPereira** [comment]
Entendi, provavelmente está no da Paula Marangoni, verei com ela. Mas o Issue foi pedido para práticas posteriores, não?

**Comment by victortxa** [comment]
:+1: 
@KarinaPereira Desde a primeira. Se você reparar esse é o da primeira prática. A idéia, na verdade, era não precisar mais criar Issues, o que acabou não acontecendo por limitação das ferramentas que usamos (aqueles links que já criavam os repositórios para vocês).

**Comment by maricardosop** [comment]
Olá Professor, agora que vi. Deve estar no da Paula. Como faço para saber com quantas práticas estou? Marília 
Enviado do Yahoo Mail no Android 

  Em 15:22 seg, 11 de jan de PM, Leonardo Uiedanotifications@github.com escreveu:  
@KarinaPereira @maricardosop nota final: 0

**Comment by leouieda** [comment]
Se acharem o repositório dessa prática postem o link aqui. Não criem uma nova issue. Qualquer coisa utilizem o link abaixo.

https://github.com/leouieda/matematica-especial/issues/3

**Comment by KarinaPereira** [comment]
Ok professor! Só para confirmar a primeira prática é a das cartas?

**Comment by leouieda** [comment]
@KarinaPereira é a de git. Veja o cronograma do curso: https://github.com/leouieda/matematica-especial/#cronograma

**Comment by KarinaPereira** [comment]
@leouieda @victortxa segue o link do repositório, nos desculpem o transtorno (somos da turma 1).
https://github.com/KarinaPereira/pratica-git.git

**Comment by leouieda** [comment]
@KarinaPereira @maricardosop @paulamarangoni
Nota: 8.5
