### ISSUE TITLE
Prática Python - Bárbara, Adélia, Daniela, Ronan

### ISSUE THREAD

**Issue by barbara-lisboa** [leouieda/matematica-especial#30]
Turma 1 - Bárbara Lisboa, Adélia Rocha, Daniela Alvim, Ronan Oliveira

https://github.com/barbara-lisboa/mat-esp-python-intro-2015.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **2**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Faltou criar a pasta onde deveria estar o script.

**Comment by leouieda** [comment]
Nota final: 10
@barbara-lisboa
