### ISSUE TITLE
Prática Python - Suani, Stefany, Filipe e Gustavo

### ISSUE THREAD

**Issue by Suani** [leouieda/matematica-especial#32]
Disciplina: Matemática Especial - Turma: 1 - Prática: Intro Python 
Alunos: Suani Suelen Boca Santa; Stefany Bento; Filipe Ribeiro; Gustavo Abrahim

https://github.com/Suani/mat-esp-python-intro-2015
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **0.5**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0.5**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **4.5**
- [x] Tarefa bônus (vale 1 pt extra): **1**
### Comentários
- Mais de um arquivo bubble-sort.py. Só vou corrigir esse: https://github.com/Suani/mat-esp-python-intro-2015/blob/master/filipe-gustavo-stefany-suani/bubble-sort.py
- a e count são nomes ruins

**Comment by leouieda** [comment]
Nota final 8.5
@Suani
