### ISSUE TITLE
Prática Git: João Felipe, Juliana de Almeida, Carla Azevedo

### ISSUE THREAD

**Issue by jfelipemaia** [leouieda/matematica-especial#38]
https://github.com/jfelipemaia/pratica-git.git

Turma 2 - 2015
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [ ] Repositório atende exatamente as especificações da prática (vale 7 pt): *\* **
- [x] Tarefa bônus (vale 1 pt extra): **1**

**Comment by leouieda** [comment]
Duplicada de #22. Fechando essa.
