### ISSUE TITLE
praticagit: Ingrid, Nara, Taina

### ISSUE THREAD

**Issue by ingridbernardo** [leouieda/matematica-especial#4]
https://github.com/ingridbernardo/pratica-git.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **1**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- alunos.txt deve conter nomes dos alunos.
- Arquivos comandos.txt deveria chamar intro-shell.txt
- Não trocou de membro do grupo durante a prática
- Não seguiu as instruções
- bubble-sort.txt deveria ter sido modificado 3 vezes

**Comment by victortxa** [comment]
@ingridbernardo  indique se vocês são da turma 1 ou 2.

**Comment by ingridbernardo** [comment]
somos turma 1.

Em 17 de setembro de 2015 10:29, victortxa notifications@github.com
escreveu:

**Comment by leouieda** [comment]
@ingridbernardo 
Nota: 4
