### ISSUE TITLE
Prática Python1 - Felipe, André, Gabriela Turma 2

### ISSUE THREAD

**Issue by gabrielateixeira** [leouieda/matematica-especial#41]
Gabriela Prates Teixeira
André Grijó
Felipe Lage

https://github.com/FelipeLage/mat-esp-python-intro-2015
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0.5**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **3**
- [x] Tarefa bônus (vale 1 pt extra): **1**
### Comentários
- O ideal é que os comentários sejam ao longo do código ao invés de concentrados e preferencialmente mensagens bem diretas de fácil e rápido entendimento.
- Programa deveria chamar bubble-sort.py não [bubble-sort-1.py](https://github.com/FelipeLage/mat-esp-python-intro-2015/blob/master/andre-felipe-gabriela/bubble-sort-1.py)
- [a](https://github.com/FelipeLage/mat-esp-python-intro-2015/blob/master/andre-felipe-gabriela/bubble-sort-1.py#L31) não é um nome bom para variavel. O que ela representa?

Tarefa 1: imprime o resultado esperado.

Tarefa 2: 
- Todas as figuras deveriam estar na pasta `fig`
- Faltou programa gerar figuras bubble-it-*.png (deveria ser [aqui](https://github.com/FelipeLage/mat-esp-python-intro-2015/blob/master/andre-felipe-gabriela/bubble-sort-1.py#L43))
- Salvando figura bubble-troca-*.png duas vezes: [antes da troca](https://github.com/FelipeLage/mat-esp-python-intro-2015/blob/master/andre-felipe-gabriela/bubble-sort-1.py#L43) e de novo [quando há troca](https://github.com/FelipeLage/mat-esp-python-intro-2015/blob/master/andre-felipe-gabriela/bubble-sort-1.py#L56)
- Faltou plotar elementos i e j

**Comment by leouieda** [comment]
Nota: 7.5
@gabrielateixeira @FelipeLage @andregrijo62
