### ISSUE TITLE
Prática Python 2: Ana Paula, João Pedro, Letícia Marinho, Maria Carolina

### ISSUE THREAD

**Issue by lemarinho** [leouieda/matematica-especial#46]
Turma 2
https://github.com/mat-esp-uerj/python-intro-2-joao_leticia_dyellen.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**`
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **0.5**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **1**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **4.5**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentarios
- Não rodou o `np.allclose` na Tarefa 3, ou seja, não conferiu o resultado.
- Nomes ruins: `for i in arquivo:`, `lista = i.split(', ')`

**Comment by victortxa** [comment]
@leouieda mesmo problema daqui https://github.com/leouieda/matematica-especial/issues/47
`NotJSONError('Notebook does not appear to be JSON: u\'\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="e...',)`

**Comment by leouieda** [comment]
@lemarinho veja o [esse ultimo commit](https://github.com/mat-esp-uerj/python-intro-2-joao_leticia_dyellen/commit/4fd1ce71f27f12f2ebe1c4f2e681cd2bdd6f8db1) que vocês fizeram. Esses `>>>> HEAD` são gerados quando há conflitos no git. Por que vocês não verificaram seu notebook antes de entregar a prática?

Arrumem isso ou não poderemos corrigir a prática. Qualquer coisa voltem numa versão anterior que não está corrompida.

**Comment by leouieda** [comment]
Vocês tem até sexta-feira 15/1

**Comment by lemarinho** [comment]
@leouieda como faço pra voltar numa versão anterior?  E voltar uma versão anterior significa que vamos perder o que fizemos no último commit?

**Comment by leouieda** [comment]
@lemarinho veja aqui http://bfy.tw/3hzo

Não precisa apagar o último. Copie o arquivo correto e faça outro commit com o arquivo não corrompido.

**Comment by lemarinho** [comment]
@leouieda Professor, eu consegui consertar o problema do arquivo corrompido com a ajuda de um amigo, mas sem querer o commit foi feito na conta dele. Espero que não tenha problema, desculpa!

**Comment by leouieda** [comment]
@lemarinho sem problemas.

**Comment by leouieda** [comment]
Nota: 8
@lemarinho
