### ISSUE TITLE
Pratica Python 2 - Luiza, Marcia, Dyellen, Rieli - Turma 2

### ISSUE THREAD

**Issue by luizagbrito** [leouieda/matematica-especial#47]
https://github.com/mat-esp-uerj/python-intro-2-marcia-luiza-rieli.git
Alunas: Luiza Brito, Marcia Ferreira, Dyellen Queiroz, Rieli
Turma 2
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **0**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **0**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **0**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Impossível avaliar pois o notebook não abre por estar corrompido. Alunos tiveram tempo e aviso para corrigir o erro mas não o fizeram.

**Comment by victortxa** [comment]
@leouieda Há algum erro que o Notebook da tarefa( https://github.com/mat-esp-uerj/python-intro-2-marcia-luiza-rieli/blob/master/tarefa-intro-python-2.ipynb )não quer abrir. Fiz download e continuou sem abrir. Parece que o arquivo foi corrompido...

**Comment by leouieda** [comment]
Cheque o código do notebook, deve ter uns `>>>>>>HEAD` perdidos no meio de algum conflito não resolvido.

Os alunos deveriam ter checado isso antes de entregar.

**Comment by victortxa** [comment]
@luizagbrito O Notebook da prática não está abrindo. O erro provavelmente ocorre conforme o @leouieda  explicou acima. Resolvam e avisem por aqui quando o notebook estiver abrindo.

**Comment by leouieda** [comment]
@luizagbrito e demais, vejam o [útlimo commit que vocês fizeram](https://github.com/mat-esp-uerj/python-intro-2-marcia-luiza-rieli/commit/308e989c21960f09b5bc06bf0cf706aad44bf355).

**Comment by leouieda** [comment]
Vocês tem até sexta-feira 15/1 para arrumar isso.

**Comment by luizagbrito** [comment]
Mandei de novo.. será que agora foi?

Em 13 de janeiro de 2016 14:54, Leonardo Uieda notifications@github.com
escreveu:

**Comment by victortxa** [comment]
@luizagbrito é só você abrir o [link](https://github.com/mat-esp-uerj/python-intro-2-marcia-luiza-rieli/blob/master/tarefa-intro-python-2.ipynb) e verificar antes. Avise quando estiver funcionando.

**Comment by leouieda** [comment]
@luizagbrito ou verifique o notebook no seu PC antes de mandar.

**Comment by leouieda** [comment]
Nota final: 0.5
@luizagbrito

**Comment by leouieda** [comment]
Nota final: 0.5
@luizagbrito
