### ISSUE TITLE
 Prática Python 2: Julyanamarapodi-Marcelaclaudio-angelicacosta-carloseduardoverissimo 

### ISSUE THREAD

**Issue by dukbom** [leouieda/matematica-especial#48]
Professor, 

Tivemos um pequeno problema na tarefa 4 e na bônus porque eu não consegui instalar o jupyter no meu computador, então eu fiz no computador do Guilherme Araujo (Gam). Só que na hora de enviar a prática pro repositório eu enviei pela conta dele e não na minha. 

Carlos Eduardo V. Ribeiro

Turma 2

https://github.com/mat-esp-uerj/python-intro-2-aguaviva.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **1**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **0.5**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0.5**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1.5**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **1**

**Comment by leouieda** [comment]
@dukbom por favor coloque aqui um link para o repositório de vocês.

**Comment by dukbom** [comment]
https://github.com/leouieda/python-intro-2

segue o link do nosso repositorio.

Att

Carlos Eduardo

2015-10-16 14:12 GMT-03:00 Leonardo Uieda notifications@github.com:

**Comment by leouieda** [comment]
@dukbom mentira. Esse repositório é o meu (veja que o link é `github.com/leouieda`). Quero saber o link do repositório do grupo.

**Comment by victortxa** [comment]
@dukbom Onde está o link correto?! O pedido aqui é de outubro. Faltam os nomes dos componentes do grupo. Lembre-se que somente as **duas menores** notas serão descartadas.

**Comment by leouieda** [comment]
@dukbom vocês tem até sexta-feira (15/1) para postar aqui o link correto da solução de vocês.

**Comment by Marcelarclaudio** [comment]
https://github.com/mat-esp-uerj/python-intro-2-aguaviva.git

**Comment by leouieda** [comment]
Nota final: 10
@dukbom @Marcelarclaudio
