### ISSUE TITLE
Pratica Git: Daniel, Julio, Marlos, Sidharta

### ISSUE THREAD

**Issue by Chalub** [leouieda/matematica-especial#5]
Turma 1
https://github.com/Chalub/pratica-git

Daniel Rosselli
Julio Cabaleiro Vianna
Marlos Thami Chalub Americo dos Reis
Sidharta Soares Pereira
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **5.5**
- [x] Tarefa bônus (vale 1 pt extra): **0.5**
### Comentários
- alunos.txt e intro-shell.txt deveriam estar em commits separados
- gostei do [commit corrigindo a tarefa errada](https://github.com/Chalub/pratica-git/commit/5201d5ef5a85d96798b62475642d3e3a74591aec). mostra que entenderam para que serve o git.
- commit do @danielrosselli deveria ter feito [isso](https://github.com/Chalub/pratica-git/commit/c133ece57e90a3b66b26dcfa98db82abd949af26)

**Comment by victortxa** [comment]
@Chalub  indique se vocês são da turma 1 ou 2.

**Comment by leouieda** [comment]
@Chalub @sidhartabuda @danielrosselli @juliocabaleiro 
Nota: 9
