### ISSUE TITLE
prática integração - Mariana, Marlos e Marilia - Turma 1

### ISSUE THREAD

**Issue by maricardosop** [leouieda/matematica-especial#53]
https://github.com/mat-esp-uerj/integracao-mmm
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.25**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0.5**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1.5**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **4.25**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentarios
- Nomes ruins: p, h, k, t, a, b
- Não respondeu a última pergunta.
- `Porque, utilizando a regra dos retângulos, a área sempre vai obter um valor maior que o valor analítico. O fator que influencia no resultado do erro é a forma do calculo, ou seja, quando o mesmo é feito manualmente sempre uma diferença no resultado final.` Sem sentido. Analiticamente não é o mesmo que manualmente. Por exemplo, você pode resolver a integral numericamente de forma manual, ao invés de fazer um código computacional.

**Comment by leouieda** [comment]
Leiam o que está escrito no repositório:

> **Crie um arquivo** chamado `alunos.txt` com os **nomes completos** de todos os integrantes do grupo. Inclua também a **qual turma** pertencem.

**Comment by leouieda** [comment]
Nota: 8
@maricardosop
