### ISSUE TITLE
Pratica Integracao - Itamar , Sidharta, Suani, Willian

### ISSUE THREAD

**Issue by ogoshi** [leouieda/matematica-especial#55]
https://github.com/mat-esp-uerj/integracao-sniper.git

Turma 1
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **0.5**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0.5**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1.5**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **4.75**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentarios
-  Nomes ruins: id, ide, e, t, e1, e2
- `inter = 0.0320570678937734`  ?
- `Não é zero por que a integração feita através da regra dos retangulos não demonstra o somatória da area abaixo da curva com exatidão, gerando assim um erro de aproximação.` Isso já está na pergunta. Vocês poderia ter discutido que o retângulo não representa bem a função, visto que está se aproximando uma curva por uma reta paralela ao eixo x.
- Na tarefa bônus a única diferença em relação às tarefas obrigatória é a função a ser integrada, curva gaussiana. O resultado (probabilidade) deveria ser aproximadamente 68%.

**Comment by leouieda** [comment]
Nota: 8.25
@ogoshi
