### ISSUE TITLE
Prática Git: Filipe Ribeiro, Gustavo Lima, Stefany Bento, Suani Santa

### ISSUE THREAD

**Issue by Stefanybento** [leouieda/matematica-especial#6]
https://github.com/Stefanybento/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **6**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- [Commit inclindo comandos do git](https://github.com/Stefanybento/pratica-git/commit/f40af1ae4621343bd2929880b5f4a9efae7beb88) deveria colocar a versão do bubble sort feita por mim em aula.

**Comment by victortxa** [comment]
@Stefanybento  indique se vocês são da turma 1 ou 2.

**Comment by Stefanybento** [comment]
Turma 1

**Comment by leouieda** [comment]
@Stefanybento @Filipeflvr @Suani @Gustavo-Abrahim 
Nota: 9
