### ISSUE TITLE
Prática Integração - Marcela Claudio, Angelica, Julyana e Carlos Eduardo

### ISSUE THREAD

**Issue by Marcelarclaudio** [leouieda/matematica-especial#62]
https://github.com/mat-esp-uerj/integracao-aguaviva.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita 
  (vale 0.5 pt): **0.5** 
- [x] Formatação do código apropriada. Ex: `espacamento = (maximo - minimo)/(N - 1)`, `indices = range(0, N, 1)`, `dado = dados[i + 1]` == BOM. `espacamento=(maximo-minimo)/ (N-1)`, `indices=range (0,N,1)`, `dado= dados [i+ 1]` == RUIM 
  (vale 0.5 pt): **0.5**
- [x] Utilizar variáveis ao invés de colocar número "na mão". Ex: `for i in range(0, N):`, `A[k][N - 1]` == BOM. `for i in range(0, 39):`, `A[k][47]` == RUIM
  (vale 1 pt): **1**
- [x] Código com comentários que explicam "por que" algo foi feito, não só "o que" foi feito
  (vale 1 pt): **0**
- [x] Nomes de variáveis descritivos. Ex: `temperatura`, `media_por_hora`, `linha`, `somatorio` == BOM. `a`, `var`, `meh`, `lista` == RUIM.
  (vale 2 pt): **1**
- [x] Código produz a solução correta (**exatamente** como especificado em "Resultado esperado")
  (vale 5 pt): **3.75**
- [x] Tarefa bônus (vale 1 pt extra): **0**
### Comentários
- Nomes  ruins: d, R, ER2, ET2
- Resposta incompleta/sem sentido na primeira pergunta (`A regra dos retangulos é apenas uma aproximacao da area real do grafico. sendo a integral mais indicada para a area de um grafico patabolico.`). 
- Segunda e terceira perguntas sem resposta.

**Comment by victortxa** [comment]
@Marcelarclaudio turma 1 ou 2?

**Comment by Marcelarclaudio** [comment]
2!!
Date: Sun, 25 Oct 2015 18:50:16 -0700

**Comment by leouieda** [comment]
@Marcelarclaudio por favor, coloque o link do repositório do seu grupo.

**Comment by victortxa** [comment]
@Marcelarclaudio Vocês não colocaram o link do repositório. Lembre-se que isso dá **nota 0**.

**Comment by Marcelarclaudio** [comment]
Ola, teve uma prática que não colocamos porque não sabíamos como se fazia, o professor viu nos avisou, e ai fiz outro issue!
Mas vou conferir aqui.

Date: Wed, 13 Jan 2016 10:39:40 -0800

**Comment by Marcelarclaudio** [comment]
Acabo de conferir, foi essa mesma, o link do repositório está no comentário

Date: Wed, 13 Jan 2016 10:39:40 -0800

**Comment by Marcelarclaudio** [comment]
https://github.com/mat-esp-uerj/integracao-aguaviva.git

**Comment by victortxa** [comment]
@Marcelarclaudio em que comentário? Está no que você colocou agora, não havia nada antes...

**Comment by Marcelarclaudio** [comment]
É , o issue tava criado na pasta errada! Mas agora você conseguiu visualizar ?
Date: Thu, 14 Jan 2016 04:51:01 -0800

**Comment by leouieda** [comment]
Nota: 6.75
@Marcelarclaudio
