### ISSUE TITLE
Prática Git: Luiza, Marcia, Gabriel

### ISSUE THREAD

**Issue by luizagbrito** [leouieda/matematica-especial#7]
Alunos: Luiza Brito, Marcia Ferreira e Gabriel Delgado

https://github.com/luizagbrito/pratica-git.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **7**
- [x] Tarefa bônus (vale 1 pt extra): **0**

**Comment by victortxa** [comment]
@luizagbrito  indique se vocês são da turma 1 ou 2.

**Comment by luizagbrito** [comment]
Turma 2! de sexta feira.

Luiza 

Enviado do meu iPhone

**Comment by leouieda** [comment]
@luizagbrito @gsdelgado @marciaferreira 
Nota: 10
