### ISSUE TITLE
Prática Git: Diana Machado, Guilherme Martins, Marcela Claudio Turma 2

### ISSUE THREAD

**Issue by Marcelarclaudio** [leouieda/matematica-especial#8]
https://github.com/Marcelarclaudio/pratica-git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **6.5**
- [x] Tarefa bônus (vale 1 pt extra): **1**
### Comentários
- alunos.txt faltando 1 nome.

**Comment by victortxa** [comment]
@Marcelarclaudio  indique se vocês são da turma 1 ou 2.

**Comment by leouieda** [comment]
@Marcelarclaudio @Gam2011 @diana06 
Nota: 10
