### ISSUE TITLE
Prática git: Carol, Juliana, Itamar

### ISSUE THREAD

**Issue by ogoshi** [leouieda/matematica-especial#9]
Turma 1
Carol Xavier
Juliana Silva
Itamar Almeida de Oliveira

https://github.com/ogoshi/pratica-git.git
## Avaliação do professor

Os itens marcados já foram corrigidos. A pontuação máxima está indicada ao lado de cada item. Os pontos obtidos estão indicados depois de `:`. A nota final será informada após terminar a correção.
- [x] Mensagens de commit que explicam claramente a mudança que foi feita (vale 3 pt): **3** 
- [x] Repositório atende exatamente as especificações da prática (vale 7 pt): **5**
- [x] Tarefa bônus (vale 1 pt extra): **1**
### Comentários
- A [resolução do conflito nesse commit](https://github.com/ogoshi/pratica-git/commit/6cc7c00ef23da91f293e6736c10660a435152519) deveria ter removido os `<<<<<<< HEAD` , `=======` e `>>>>>>> 11aeb72df09cd65e7f268571845f1e958880b9f3`. No final deveria conter só o código.
- [alunos.txt](https://github.com/ogoshi/pratica-git/blob/master/alunos.txt) e [intro-shell.txt](https://github.com/ogoshi/pratica-git/blob/master/intro-shell.txt) vazios.

**Comment by victortxa** [comment]
@ogoshi  indique se vocês são da turma 1 ou 2.

**Comment by ogoshi** [comment]
Turma 1

**Comment by leouieda** [comment]
@ogoshi @julianadesilva @carollxsv
Nota: 9
