### ISSUE TITLE
Chapatime Práticas matrizes e vetores \ integraçao

### ISSUE THREAD

**Issue by Chapaman** [leouieda/matematica-especial#98]
Thiago Franklin; Arthur Romeu; Nara de Oliveira; Felipe
https://github.com/mat-esp-uerj/matrizes-vetores-chapatime.git
https://github.com/mat-esp-uerj/integracao-chapatime.git

**Comment by Chapaman** [comment]
turma 1

**Comment by leouieda** [comment]
@Chapaman por favor, crie duas issues separadas para cada prática

**Comment by leouieda** [comment]
@Chapaman @ThiagoFranklin @nararodrigues @felipesurf por favor, criem duas issues **separadas** para cada prática. Vocês tem até semana que vem.

**Comment by leouieda** [comment]
Obrigado.

Obs: separa em #115 e #116
